name       : twolame
version    : 0.3.13
release    : 2
source     :
    - http://sourceforge.net/projects/twolame/files/twolame/0.3.13/twolame-0.3.13.tar.gz : 98f332f48951f47f23f70fd0379463aff7d7fb26f07e1e24e42ddef22cc6112a
license    : LGPL-2.1
component  : multimedia.codecs
optimize   : speed
summary    : TwoLAME is an optimized MPEG Audio Layer 2 (MP2) encoder. 
description: |
    TwoLAME is an optimized MPEG Audio Layer 2 (MP2) encoder.
    It is based heavily on:

    - tooLAME by Michael Cheng
    - the ISO dist10 code
    - improvement to algorithms as part of the LAME project (lame.sf.net)
    - other contributors (see AUTHORS)

    TwoLAME should be able to be used as a drop-in replacement for
    LAME (a MPEG Layer 3 encoder). The frontend takes very similar
    command line options to LAME, and the backend library has a very
    similar API to LAME.
builddeps  :
    - pkgconfig(sndfile)
setup      : |
    CFLAGS+=" -funroll-loops"
    %configure --disable-static
build      : |
    CFLAGS+=" -funroll-loops"
    %make
install    : |
    %make_install
